# Generated by Django 5.2.6 on 2025-10-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='buyer', help_text='Type of user account', max_length=10),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(choices=[('junior', 'Junior Admin'), ('senior', 'Senior Admin'), ('super', 'Super Admin')], default='junior', max_length=20)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_orders', models.BooleanField(default=False)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_manage_system', models.BooleanField(default=False)),
                ('last_admin_action', models.DateTimeField(blank=True, null=True)),
                ('admin_actions_count', models.PositiveIntegerField(default=0)),
                ('ip_whitelist', models.TextField(blank=True, help_text='Comma-separated IP addresses')),
                ('require_2fa', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('role_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_admin_profile',
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_shipping_method', models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('overnight', 'Overnight Shipping')], default='standard', max_length=50)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('newsletter_subscription', models.BooleanField(default=True)),
                ('deal_notifications', models.BooleanField(default=True)),
                ('product_recommendations', models.BooleanField(default=True)),
                ('is_verified_buyer', models.BooleanField(default=False)),
                ('buyer_rating', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_buyer_profile',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('corporation', 'Corporation')], default='individual', max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('business_address', models.TextField(blank=True)),
                ('products_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seller_rating', models.FloatField(default=5.0)),
                ('response_time_hours', models.PositiveIntegerField(default=24)),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('store_description', models.TextField(blank=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('is_verified_seller', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('can_sell', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_seller_profile',
            },
        ),
    ]
