# Generated by Django 5.2.6 on 2025-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type_adminprofile_buyerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbusinessinfo',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
